CREATE DATABASE todo;
USE todo;
CREATE TABLE tasks(id int NOT NULL AUTO_INCREMENT PRIMARY KEY,task varchar(255));
CREATE USER 'php'@'127.0.0.1' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'php'@'127.0.0.1';
FLUSH PRIVILEGES;
